name: dev-build-deploy

on:
  push:
    branches:
      - fix-projects-page-styles-add-infinite-scroll

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: actions/aws/cli@master
      - name: install dependencies
        run: yarn
      - name: lint
        run: yarn lint
      - name: tsc
        run: yarn tsc
      - name: build
        run: yarn build && yarn export
      - name: dev deploy
        run: aws s3 sync out/. s3://dev.blocks.directory/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
